# GOD DAMN, ACTUALLY WORKING WORKFLOF??????
name: build apk

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: setup oracle hellhole
        uses: actions/setup-java@v6
        with:
          distribution: 'oracle'
          java-version: 'latest'
          cache: 'gradle'

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > tspigot_release_key.jks
        
      - name: chmooooooood
        run: chmod +x ./gradlew

      - name: build app
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease

      - name: Move files
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/app-release.apk

      - name: Sign App
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs
          signingKey: ${{ secrets.ANDROID_KEYSTORE }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: upload debug apk
        uses: actions/upload-artifact@v7
        with:
          name: tspigotradio-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          archive: false

      - name: upload release apk
        uses: actions/upload-artifact@v7
        with:
          name: tspigotradio-release
          path: app/build/outputs/app-release-signed.apk
          archive: false
          
      # ?????????????
      # PROFIT!
