# GOD DAMN, ACTUALLY WORKING WORKFLOF??????
name: build apk

on:

  push:
    branches:
      - 'master/**'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: setup oracle hellhole
        uses: actions/setup-java@v6
        with:
          distribution: 'oracle'
          java-version: 'latest'
          cache: 'gradle'

      - name: chmooooooood
        run: chmod +x ./gradlew

      # no idea if i even need it
      - name: run test
        run: ./gradlew test

      - name: build gradlew
        run: ./gradlew build

      - name: build app
        run: ./gradlew assembleDebug

      - name: upload it
        uses: actions/upload-artifact@v7
        with:
          name: tspigotradio
          path: app/build/outputs/apk/debug/app-debug.apk
          archive: false

      # ?????????????
      # PROFIT!
